## Concatenar records

Notebook para concatenar diferentes batimentos

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
records = ['426627000','426783006']

In [3]:
df = pd.read_csv('../beats/data_beat_'+records[0]+'.csv')
df2 = pd.read_csv('../beats/data_beat_'+records[1]+'.csv')

In [4]:
df

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,318,319,320,321,322,323,324,325,326,327
0,0,-0.007,-0.010,-0.012,-0.007,-0.003,-0.002,-0.002,-0.005,-0.019,...,0.001,-0.015,-0.030,-0.029,-0.018,-0.012,-0.010,-0.006,426627000.0,0.0
1,1,-0.014,-0.005,-0.001,0.003,0.019,0.030,0.038,0.033,0.025,...,0.020,0.023,0.023,0.021,0.011,0.008,0.011,0.003,426627000.0,0.0
2,2,-0.005,0.010,0.027,0.021,0.021,0.011,0.002,0.000,-0.004,...,-0.037,-0.030,-0.013,-0.004,-0.007,-0.017,-0.020,-0.025,426627000.0,0.0
3,3,0.015,0.030,0.018,-0.004,-0.013,-0.012,0.000,-0.002,0.001,...,0.004,-0.008,-0.017,-0.009,-0.007,0.001,-0.007,-0.025,426627000.0,0.0
4,4,0.035,0.031,0.030,0.026,0.016,-0.003,-0.009,0.000,-0.004,...,0.001,-0.015,-0.012,-0.007,-0.010,-0.008,-0.005,-0.002,426627000.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2372,2,-0.005,-0.003,-0.003,-0.006,-0.006,-0.006,-0.005,-0.004,-0.004,...,-0.008,-0.007,-0.007,-0.007,-0.011,-0.016,-0.018,-0.021,426627000.0,0.0
2373,3,-0.010,-0.009,-0.008,-0.007,-0.007,-0.004,-0.002,-0.001,-0.002,...,-0.029,-0.026,-0.028,-0.033,-0.038,-0.040,-0.039,-0.037,426627000.0,0.0
2374,4,-0.026,-0.024,-0.022,-0.022,-0.021,-0.019,-0.019,-0.018,-0.021,...,-0.023,-0.022,-0.021,-0.019,-0.018,-0.018,-0.020,-0.023,426627000.0,0.0
2375,5,0.019,0.014,0.013,0.015,0.020,0.026,0.032,0.039,0.045,...,-0.032,-0.037,-0.038,-0.040,-0.042,-0.043,-0.044,-0.045,426627000.0,0.0
2376,6,-0.003,0.002,0.008,0.013,0.015,0.015,0.014,0.013,0.011,...,-0.035,-0.034,-0.033,-0.032,-0.031,-0.029,-0.025,-0.023,426627000.0,0.0

In [5]:
df = df.drop(columns=['Unnamed: 0'])

In [6]:
df2 = df2.drop(columns=['Unnamed: 0'])

In [7]:
df_concat = pd.concat([df,df2])

In [8]:
df_concat

,0,1,2,3,4,5,6,7,8,9,...,318,319,320,321,322,323,324,325,326,327
0,-0.007,-0.010,-0.012,-0.007,-0.003,-0.002,-0.002,-0.005,-0.019,-0.013,...,0.001,-0.015,-0.030,-0.029,-0.018,-0.012,-0.010,-0.006,426627000.0,0.0
1,-0.014,-0.005,-0.001,0.003,0.019,0.030,0.038,0.033,0.025,0.013,...,0.020,0.023,0.023,0.021,0.011,0.008,0.011,0.003,426627000.0,0.0
2,-0.005,0.010,0.027,0.021,0.021,0.011,0.002,0.000,-0.004,-0.004,...,-0.037,-0.030,-0.013,-0.004,-0.007,-0.017,-0.020,-0.025,426627000.0,0.0
3,0.015,0.030,0.018,-0.004,-0.013,-0.012,0.000,-0.002,0.001,0.007,...,0.004,-0.008,-0.017,-0.009,-0.007,0.001,-0.007,-0.025,426627000.0,0.0
4,0.035,0.031,0.030,0.026,0.016,-0.003,-0.009,0.000,-0.004,-0.010,...,0.001,-0.015,-0.012,-0.007,-0.010,-0.008,-0.005,-0.002,426627000.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3360,0.004,0.005,0.005,0.010,0.042,0.071,0.073,0.060,0.052,0.042,...,0.007,-0.001,-0.010,-0.016,-0.015,-0.015,-0.015,-0.033,426783006.0,0.0
3361,0.069,0.040,-0.030,-0.022,-0.004,-0.010,-0.022,-0.030,-0.043,-0.010,...,-0.029,-0.035,-0.029,-0.029,-0.025,-0.048,-0.073,-0.066,426783006.0,0.0
3362,-0.030,-0.042,-0.055,-0.064,-0.073,-0.085,-0.092,-0.106,-0.106,-0.092,...,-0.208,-0.208,-0.155,-0.110,-0.073,-0.069,-0.090,-0.105,426783006.0,0.0
3363,-0.088,-0.089,-0.082,-0.079,-0.075,-0.067,-0.025,0.034,0.070,0.065,...,-0.133,-0.165,-0.157,-0.051,0.080,0.123,0.065,0.018,426783006.0,0.0
3364,-0.056,-0.060,-0.085,-0.071,-0.053,-0.034,-0.028,-0.060,-0.088,-0.116,...,0.014,-0.030,-0.061,-0.091,-0.105,-0.105,-0.105,-0.104,426783006.0,0.0

In [9]:
df_concat.to_csv("batimentos.csv")